version: '3.8'

services:
  api:
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    volumes:
      - ../app:/app
    environment:
      - PYTHONUNBUFFERED=1

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboard_template.json:/var/lib/grafana/dashboards/dashboard_template.json
