name: MLflow CI CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run modelling and tuning
        env:
          DAGSHUB_REPO_OWNER: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_REPO_NAME: Eksperimen_SML_Nurul-Fitriah
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run . --experiment-name "Eksperimen_SML_Nurul-Fitriah" --env-manager=local

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(cat run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest MLflow Run ID: $RUN_ID"

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            tmp_artifacts/estimator.html
            tmp_artifacts/metric_info.json
            tmp_artifacts/training_confusion_matrix.png
            tmp_artifacts/feature_importance.png
            tmp_artifacts/data_schema.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-model:latest ./app
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-model:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-model:${{ env.RUN_ID }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-model:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-scoring-model:${{ env.RUN_ID }}

      - name: Complete job
        run: echo "CI/CD pipeline completed successfully!"
